name: stock-prediction-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - azureml-sdk
    - pandas
    - numpy
    - scikit-learn
    - xgboost
    - lightgbm
    - tensorflow
    - mlflow
    - yfinance
