name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        activate-environment: myenv
        environment-file: environment.yml  # Use this if you have a Conda environment file
        auto-activate-base: false

    - name: Install dependencies with Conda
      run: |
        conda install pandas numpy scikit-learn xgboost -y  # Conda-managed packages
        conda install pytz scipy threadpoolctl -y

    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt  # Pip-managed packages

    - name: Run your deployment script
      run: |
        python deploy.py  # Example of running your deployment script

    - name: Verify installation
      run: |
        pip list  # Check installed packages to verify if everything was installed correctly
