name: Setup MLOps Project Structure

on:
  workflow_dispatch:

jobs:
  setup_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Updated to v4

    - name: Create test file
      run: |
        echo "# Test File" > test.md
        git status
        git diff

    - name: Check for changes
      id: git-check
      run: |
        if git diff --exit-code; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit changes
      if: steps.git-check.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add test file" -a

    - name: Push changes
      if: steps.git-check.outputs.changed == 'true'
      run: git push

    - name: Check for errors
      if: failure()
      run: |
        echo "Workflow failed. Here's some debugging information:"
        git status
        git log --oneline -n 5
        echo "Current directory contents:"
        ls -R
