name: Setup MLOps Project Structure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Create project structure
      run: |
        mkdir -p .github/workflows
        mkdir -p src/{data,models,utils}
        mkdir -p notebooks
        mkdir -p tests
        mkdir -p config
        mkdir -p scripts

    - name: Create initial files
      run: |
        echo "# MLOps-Stock" > README.md
        echo "name: Train Model" > .github/workflows/train_model.yml
        echo "# Data preparation functions" > src/data/data_preparation.py
        echo "# Stock prediction pipeline" > src/models/stock_prediction_pipeline.py
        echo "# Helper functions" > src/utils/helper_functions.py
        echo "# Exploratory Data Analysis" > notebooks/exploratory_data_analysis.ipynb
        echo "# Test data preparation" > tests/test_data_preparation.py
        echo "# Test stock prediction pipeline" > tests/test_stock_prediction_pipeline.py
        echo "{}" > config/config.json
        echo "# Model deployment configuration" > config/deployment_config.yml
        echo "# Inference configuration" > config/inference_config.yml
        echo "# Azure ML training script" > scripts/train_aml.py
        echo "# Model deployment script" > scripts/deploy_model.py
        echo "# Project dependencies" > requirements.txt
        echo ".env\nvenv/\n__pycache__/\n*.pyc" > .gitignore

    - name: Check for changes
      id: git-check
      run: |
        git status
        git diff
        echo "::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)"

    - name: Commit changes
      if: steps.git-check.outputs.modified == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Set up MLOps project structure" -a || echo "No changes to commit"

    - name: Push changes
      if: steps.git-check.outputs.modified == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: Check for errors
      if: failure()
      run: |
        echo "Workflow failed. Here's some debugging information:"
        git status
        git log --oneline -n 5
        echo "Current directory contents:"
        ls -R
